# Generated by Django 5.0.2 on 2024-02-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('episodes', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('rating', models.FloatField()),
                ('studio', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
